name: CI · Run Cypress Tests

on:
  pull_request:
    branches: [develop]

jobs:
  component-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - run: |
          npm ci
      # build only if your component tests need it
      - run: npm run build
      - run: npx cypress run --component

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: |
          npx serve -s dist -l 4173 &       # serve your production bundle
          npx wait-on http://localhost:4173
      - run: npx cypress run
