on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x','20.x','22.x']
    env:
      # Ensure these secrets are set in your repository settings
      MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build for E2E
        run: npm run render‑build    # or your correct build script
      - name: Start server and wait
        run: |
          npm run start &
          npx wait-on http://localhost:3001 --timeout 60
      - name: Run Cypress E2E
        run: npx cypress run
