# .github/workflows/deploy-render.yml
name: CD · Deploy to Render

# trigger on merges to main/develop or manual dispatch
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  render-deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Trigger Render via Webhook
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
